package ai.appdna.sdk

// SPEC-070-A J.14 — generated by AGP from `buildFeatures { buildConfig = true }`.
// Class lives in package `ai.appdna.sdk` (matches the `namespace` declared in
// build.gradle.kts), so the import is the same package; we leave it explicit
// so reviewers see the dependency at a glance.

/**
 * SDK environment targeting.
 */
enum class Environment(val baseUrl: String) {
    // Both environments share the same backend host — iOS parity. The
    // SANDBOX vs PRODUCTION distinction is enforced by API-key prefix
    // (adn_test_* vs adn_live_*) which the backend routes accordingly.
    // iOS reference: Core/Network/APIClient.swift:107-108.
    PRODUCTION("https://api.appdna.ai"),
    SANDBOX("https://api.appdna.ai")
}

/**
 * Log verbosity levels.
 */
enum class LogLevel(val level: Int) {
    NONE(0),
    ERROR(1),
    WARNING(2),
    INFO(3),
    DEBUG(4)
}

/**
 * SPEC-070-A finalization Phase C — app-level forced theme override.
 * Mirrors iOS `ForcedTheme` enum. Pass to `AppDNA.setForcedTheme(...)`.
 */
enum class ForcedTheme {
    LIGHT,
    DARK,
    SYSTEM,
}

/**
 * SPEC-070-B PN row 6 (N1) — the billing backend the SDK dispatches purchases through.
 *
 * iOS has carried `BillingProvider` since SPEC-027 (`Configuration.swift:23`); Android auto-detected
 * from the classpath, which left Adapty's `apiKey` with nowhere to live. The case names are iOS's,
 * deliberately: they are the wire tags pinned by the `billing_provider_adapty_tagged_map` shared
 * fixture, and a cross-platform wrapper must encode the same string on both platforms.
 *
 * On Android [StoreKit2] means Google Play Billing — the platform's own store. The name is a
 * cross-platform tag, not a claim about which framework is linked.
 *
 * The value-less cases cross the wrapper channel as bare strings; [Adapty] crosses as the tagged map
 * `{"type":"adapty","apiKey":"..."}`.
 */
sealed class BillingProvider(val type: String) {
    /** The platform store: Google Play Billing on Android, StoreKit 2 on iOS. */
    object StoreKit2 : BillingProvider("storeKit2")
    object RevenueCat : BillingProvider("revenueCat")
    /** Adapty, with the publishable SDK key it needs to start. */
    data class Adapty(val apiKey: String) : BillingProvider("adapty")
    /** No billing. Purchases and entitlement reads fail fast rather than silently no-op. */
    object None : BillingProvider("none")

    companion object {
        /**
         * Decode the wrapper wire form: a bare string for the value-less cases, or a tagged map for
         * [Adapty]. Returns null on anything else, so a caller can decide between a default and an
         * error rather than having one chosen for it.
         */
        @JvmStatic
        fun fromWire(value: Any?): BillingProvider? = when (value) {
            is BillingProvider -> value
            is String -> when (value) {
                "storeKit2" -> StoreKit2
                "revenueCat" -> RevenueCat
                "none" -> None
                // A bare "adapty" carries no apiKey, so it cannot be honored.
                else -> null
            }
            is Map<*, *> -> {
                val type = value["type"] as? String
                val apiKey = value["apiKey"] as? String
                when {
                    type == "adapty" && !apiKey.isNullOrEmpty() -> Adapty(apiKey)
                    type == "storeKit2" -> StoreKit2
                    type == "revenueCat" -> RevenueCat
                    type == "none" -> None
                    else -> null
                }
            }
            else -> null
        }
    }

    /** Re-encode to the wire form. Lossless round-trip with [fromWire]. */
    fun toWire(): Any = when (this) {
        is Adapty -> mapOf("type" to "adapty", "apiKey" to apiKey)
        else -> type
    }
}

/**
 * Configuration options for the AppDNA SDK.
 */
data class AppDNAOptions(
    /** Automatic flush interval in seconds. Default: 30. */
    val flushInterval: Long = 30L,
    /** Number of events per flush batch. Default: 20. */
    val batchSize: Int = 20,
    /** Remote config cache TTL in seconds. Default: 3600 (1 hour). SPEC-067. */
    val configTTL: Long = 3600L,
    /** Log verbosity. Default: WARNING. */
    val logLevel: LogLevel = LogLevel.WARNING,
    /**
     * SPEC-070-A H.21 — host-supplied small-icon drawable resource id used
     * for AppDNA push notifications. When `0`, [AppDNAMessagingService]
     * falls through to manifest `<meta-data
     * android:name="com.google.firebase.messaging.default_notification_icon">`
     * and finally `applicationInfo.icon`.
     */
    val notificationIcon: Int = 0,
    /**
     * SPEC-070-C D4 — SDK-wrapper attribution (`native` | `flutter` | `react_native`),
     * tagged on every event's device context (→ BigQuery `framework` column). Defaults
     * to `native`; the Flutter/RN wrappers pass their identity via configure().
     */
    val framework: String = "native",
    /**
     * SPEC-070-C — the wrapper SDK's OWN published version (e.g. Flutter "1.0.5"),
     * so diagnose() reports the wrapper version per platform. null for native hosts.
     */
    val frameworkVersion: String? = null,
    /**
     * SPEC-070-B PN row 6 (N1) — billing backend. Defaults to [BillingProvider.StoreKit2]
     * (Google Play Billing on Android), matching iOS's `.storeKit2` default.
     */
    val billingProvider: BillingProvider = BillingProvider.StoreKit2,
    /**
     * SPEC-070-B PN row 14 (AC-36) — when true, analytics stay OFF until the host calls
     * `setConsent(analytics)`, and no event (including `sdk_initialized`) is emitted before that
     * decision. When false — the default, preserving today's behavior — analytics are opt-out.
     *
     * Either way the decision is now **persisted**: `setConsent(false)` used to be silently undone
     * by the next cold start.
     */
    val requireConsent: Boolean = false,
    /**
     * SPEC-070-B PN row 16 (W12) — how long a wrapper waits for a host veto (seconds) before
     * applying the hook's default. Surfaced through `diagnose()`.
     */
    val vetoTimeout: Long = 5L
)

/**
 * Internal logger.
 *
 * SPEC-070-A G.22: Lambda-variant API — message providers are only invoked when
 * the level is enabled, so callers can safely build expensive strings (e.g. JSON
 * dumps) without paying the cost when `LogLevel.WARNING` is the floor.
 *
 * Both lambda + string forms are supported so existing call sites compile
 * unchanged. New call sites should prefer the lambda variant:
 *
 *     Log.debug { "Tracked event: $event with ${properties?.size} props" }
 *
 * SPEC-070-A J.14: in non-debug (release) builds we additionally clamp INFO and
 * DEBUG to no-op even when callers leave [LogLevel.DEBUG] configured — that way
 * a chatty production app doesn't flood logcat. ERROR + WARN always print.
 *
 * The gating is BuildConfig-driven so it survives ProGuard/R8 stripping in
 * release builds (R8 will inline `BuildConfig.DEBUG = false` and elide the
 * disabled branches entirely).
 */
internal object Log {
    var level: LogLevel = LogLevel.WARNING

    // SPEC-070-A J.14 — derived once at class-load time. R8 inlines
    // `BuildConfig.DEBUG` so the release-build check costs nothing at runtime.
    private val isDebugBuild: Boolean = BuildConfig.DEBUG

    fun error(messageProvider: () -> String) {
        if (level.level >= LogLevel.ERROR.level) println("[AppDNA][ERROR] ${messageProvider()}")
    }

    fun warning(messageProvider: () -> String) {
        if (level.level >= LogLevel.WARNING.level) println("[AppDNA][WARN] ${messageProvider()}")
    }

    fun info(messageProvider: () -> String) {
        // J.14 — INFO is verbose; suppress entirely in release builds.
        if (!isDebugBuild) return
        if (level.level >= LogLevel.INFO.level) println("[AppDNA][INFO] ${messageProvider()}")
    }

    fun debug(messageProvider: () -> String) {
        if (!isDebugBuild) return
        if (level.level >= LogLevel.DEBUG.level) println("[AppDNA][DEBUG] ${messageProvider()}")
    }

    // String overloads for backward compatibility with existing call sites.
    // `Log.warning("msg")` continues to work alongside `Log.warning { "msg" }`.
    fun error(message: String) {
        if (level.level >= LogLevel.ERROR.level) println("[AppDNA][ERROR] $message")
    }

    fun warning(message: String) {
        if (level.level >= LogLevel.WARNING.level) println("[AppDNA][WARN] $message")
    }

    fun info(message: String) {
        if (!isDebugBuild) return
        if (level.level >= LogLevel.INFO.level) println("[AppDNA][INFO] $message")
    }

    fun debug(message: String) {
        if (!isDebugBuild) return
        if (level.level >= LogLevel.DEBUG.level) println("[AppDNA][DEBUG] $message")
    }
}
